[build]
  base = "docs/"
  publish = "public/"
  command = "npm run build"

[[redirects]]
  from = "/decorators/*"
  to = "/language/decorators/:splat"
  status = 200

[[redirects]]
  from = "/examples/*"
  to = "/examples/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
